### ISSUE TITLE
Implement query string support in the list function

### ISSUE THREAD

**Issue by vicscotoni** [CSCI-GA-2820-SP24-001/orders#40]
**As a** developer
**I need** the List function to process query strings,
**So that** the API can return filtered results based on the query
   
 ### Details and Assumptions
 * The List function currently does not interpret or use query strings
 * Proper utilization of query strings can significantly enhance the API's flexibility
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given a query string is provided in the List method call,
 When the List function processes this call,
 Then it should parse the query string and apply the filtering before returning the results.
```

**Comment by frybin** [comment]
Examples:
https://github.com/nyu-devops/lab-flask-bdd/blob/master/service/routes.py#L49-L83
https://github.com/nyu-devops/lab-flask-bdd/blob/master/service/models.py#L177-L245

Our Code:
https://github.com/CSCI-GA-2820-SP24-001/orders/blob/master/service/routes.py#L186-L198
https://github.com/CSCI-GA-2820-SP24-001/orders/blob/master/service/models.py#L134-L138
