### ISSUE TITLE
 Create a new endpoint for a resource-specific action (e.g., Liking a Product)

### ISSUE THREAD

**Issue by vicscotoni** [CSCI-GA-2820-SP24-001/orders#41]
**As a** developer, 
**I need** to create an endpoint for users to like a product 
**So that** users can interact with products beyond standard operations.  
   
 ### Details and Assumptions
 * Users currently can only perform standard operations on products
 * Adding the ability to "like" a product could increase user engagement
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given a user wants to like a product
 When they send a request the like action endpoint with the product's ID
 Then the product's like count should increment and the action should be recorded 
```

**Comment by frybin** [comment]
Example:
https://github.com/nyu-devops/lab-flask-bdd/blob/master/service/routes.py#L186-L213

Our:
https://github.com/CSCI-GA-2820-SP24-001/orders/blob/master/service/routes.py#L257
