### ISSUE TITLE
Maintain code coverage 95% 

### ISSUE THREAD

**Issue by jones12k** [CSCI-GA-2820-SP24-001/orders#53]
**As a** Developer
**I need** GitHub Actions to access the code coverage of any push/pull request
**So that** Any push/pull request that has test coverage below 95% does not merge with the master
   
 ### Details and Assumptions
 * Code coverage reports are generated and accessible.
 * The codebase already has a sufficient test coverage.
 * GitHub Actions is configured for the repository
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given code coverage reports are generated and accessible

 When someone creates a pull request to merge changes into the master branch

 Then GitHub Actions should automatically trigger
 And check the code coverage

 And if the code coverage drops below 95%
 Then the pull request should be marked as failed
 And merging should be blocked
 And relevant stakeholders should be notified
```

**Comment by frybin** [comment]
Closing issue because we should be able to just keep Code Coverage
